config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  root 'home#index'
  get 'home/about' => 'home#about'
  get 'home/lookup' => 'home#lookup'
  post 'home/lookup' => 'home#lookup'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user?, only: %i[ show edit update destroy ]
  before_action :set_crypto, only: %i[ show edit update destroy ]
  before_action :created_by_current_user?, only: %i[ create ]
  before_action :redirect_if_invalid_symbol, only: %i[ create ]

  # GET /cryptos or /cryptos.json
  def index
    @cryptos = current_user.cryptos
    @crypto_listings = helpers.crypto_listings_api_call
    @total_profit_loss = 0
  end

  # GET /cryptos/1 or /cryptos/1.json
  def show
    @crypto_name = params[:crypto_name]
  end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit
    @crypto_name = params[:crypto_name]
  end

  # POST /cryptos or /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: "Crypto was successfully created." }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1 or /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: "Crypto was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1 or /cryptos/1.json
  def destroy
    @crypto.destroy
    respond_to do |format|
      format.html { redirect_to cryptos_url, notice: "Crypto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crypto
      @crypto = Crypto.find(params[:id])
    end

    # Prevent user from accessing resources that don't belong to them
    def correct_user?
      unless current_user.cryptos.find_by(id: params[:id])
        redirect_to cryptos_path, notice: "Not authorized."
      end
    end

    # Prevent user from creating resources for other users
    def created_by_current_user?
      unless params[:crypto][:user_id].to_i == current_user.id
        redirect_to cryptos_path, notice: "Not authorized."
        return
      end
    end

    # Only allow a list of trusted parameters through.
    def crypto_params
      params.require(:crypto).permit(:symbol, :user_id, :cost_per, :amount_owned)
    end

    def redirect_if_invalid_symbol
      @crypto_listings = helpers.crypto_listings_api_call
      @crypto_listings.each do |listing|
        if listing['symbol'] == params[:crypto][:symbol].upcase
          return
        end
      end
      
      redirect_to cryptos_path, notice: "Unable to add #{params[:crypto][:symbol]}."
      return
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @coins = helpers.crypto_listings_api_call
    @topranked = @coins.select { |coin| coin["cmc_rank"] <= 12 }.sort_by { |coin| coin['cmc_rank'] }
  end

  def about
  end

  def lookup
    @symbol = params[:crypto_symbol]
    if @symbol
      @coins = helpers.crypto_listings_api_call
      @coin = @coins.select { |coin| coin["symbol"] == @symbol.upcase}[0] || {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def crypto_listings_api_call
    @url = "https://pro-api.coinmarketcap.com/v1/cryptocurrency/listings/latest?CMC_PRO_API_KEY=#{ENV['CMC_PRO_API_KEY']}"
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    return @coins = JSON.parse(@response)["data"]
  end
end

app/helpers/cryptos_helper.rb
module CryptosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto) do |form| %>
  <% if crypto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
        <% crypto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% unless params[:action] == "edit" %>
    <div class="field">
      <%= form.label :symbol %>
      <%= form.text_field :symbol, class: "form-control" %>
    </div>
  <% end %>

  <div class="field hidden">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, value: current_user.id, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :cost_per %>
    <%= form.text_field :cost_per, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :amount_owned %>
    <%= form.text_field :amount_owned, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-default" %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1><%= @crypto_name %></h1>
<br/>

<div class="panel panel-default">
  <div class="panel-heading">Editing Crypto</div>
  <div class="panel-body">
    <%= render 'form', crypto: @crypto %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Back', cryptos_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/cryptos/index.html.erb
<h1>Your Portfolio</h1>
<br/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Market Price (USD)</th>
      <th>Current Rank</th>      
      <th>Pct. Change (1h)</th>
      <th>Pct. Change (24h)</th>
      <th>Pct. Change (7d)</th>
      <th>Current Value (USD)
      <th>Average Cost (USD)</th>
      <th>Total Return (USD)</th>
      <th>Quantity Owned</th>
    </tr>
  </thead>

  <tbody>
    <% @crypto_listings.sort_by { |x| x['cmc_rank'] }.each do |listing| %>
      <% @cryptos.each do |crypto| %>
        <% if crypto.symbol.upcase == listing['symbol'] %>
          <tr>
            <td><%= link_to "#{listing['name']} (#{listing['symbol']})", crypto_path(crypto, :crypto_name => listing['name']) %></td>         
            <td><%= listing['quote']['USD']['price'].to_d.round(8) %></td>
            <td><%= listing['cmc_rank'] %></td>
            <td><%= listing['quote']['USD']['percent_change_1h'].round(2) %></td>
            <td><%= listing['quote']['USD']['percent_change_24h'].round(2) %></td>
            <td><%= listing['quote']['USD']['percent_change_7d'].round(2) %></td>
            <td><%= (listing['quote']['USD']['price'].to_d * crypto.amount_owned).round(8) %></td>            
            <td><%= crypto.cost_per.round(8) %></td>
            <td><%= ((listing['quote']['USD']['price'].to_d - crypto.cost_per) * crypto.amount_owned).round(8) %></td>
            <td><%= crypto.amount_owned.round(8) %></td>
            <% @total_profit_loss += ((listing['quote']['USD']['price'].to_d - crypto.cost_per) * crypto.amount_owned) %>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<strong>Total Portfolio Revenue (USD): </strong><%= @total_profit_loss.round(8) %>
<br/>
<br/>
<br/>

<%= link_to 'New Crypto', new_crypto_path, role: 'button', class: 'btn btn-default' %>

app/views/cryptos/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">New Crypto</div>
  <div class="panel-body">
    <%= render 'form', crypto: @crypto %>
  </div>
  <div class="panel-footer">
    <%= link_to 'Back', cryptos_path %>
  </div>
</div>

app/views/cryptos/show.html.erb
<h1><%= @crypto_name %></h1>
<br/>

<div class="panel panel-default">
  <div class="panel-heading">Details</div>
  <div class="panel-body">
    <p>
      <strong>Cost per:</strong>
      <%= @crypto.cost_per.round(8) %>
    </p>

    <p>
      <strong>Amount owned:</strong>
      <%= @crypto.amount_owned.round(8) %>
    </p>
  </div>
  <div class="panel-footer">
    <%= link_to 'Back', cryptos_path, class: 'btn btn-default' %>
    <%= link_to 'Edit', edit_crypto_path(@crypto, :crypto_name => @crypto_name), class: 'btn btn-default' %>
    <%= link_to 'Delete', @crypto, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger active' %>
  </div>
</div>

app/views/home/_flash_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close" data-dismiss="alert">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Crypto Portfolio Tracker", root_path, class: "navbar-brand" %> 
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", home_about_path %></li>
        <li><%= link_to "Lookup", home_lookup_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Add New", new_crypto_path %></li>
        <li><%= link_to "View Portfolio", cryptos_path %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Signup", new_user_registration_path %></li> 
      <% end %>
  
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_single_coin_info_panel.html.erb
<div class="panel panel-default">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Current Market Price (USD)</th>
        <th>Current Rank</th>      
        <th>Pct. Change (1h)</th>
        <th>Pct. Change (24h)</th>
        <th>Pct. Change (7d)</th>
    </thead>

    <tbody>
      <tr>
        <td><%= @coin['name'] %> (<%= @coin['symbol']%>) </td>         
        <td><%= @coin['quote']['USD']['price'].to_d.round(8) %></td>
        <td><%= @coin['cmc_rank'] %></td>
        <td><%= @coin['quote']['USD']['percent_change_1h'].round(2) %></td>
        <td><%= @coin['quote']['USD']['percent_change_24h'].round(2) %></td>
        <td><%= @coin['quote']['USD']['percent_change_7d'].round(2) %></td>        
      </tr>
    </tbody>
  </table>
</div>

app/views/home/about.html.erb
<h1>About Page</h1>
<br/>

<p><strong>Crypto Portfolio Tracker</strong> helps users track their cryptocurrency holdings in a single uncluttered tool. We hope you find it useful!</p>

app/views/home/index.html.erb
<h1>Top Ranked</h1>
<br/>

<table class="table table-striped table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current Market Price (USD)</th>
      <th>Current Rank</th>      
      <th>Pct. Change (1h)</th>
      <th>Pct. Change (24h)</th>
      <th>Pct. Change (7d)</th>
  </thead>

  <tbody>
    <% @topranked.each do |crypto| %>
      <tr>
        <td><%= crypto['name'] %> (<%= crypto['symbol']%>) </td>         
        <td><%= crypto['quote']['USD']['price'].to_d.round(8) %></td>
        <td><%= crypto['cmc_rank'] %></td>
        <td><%= crypto['quote']['USD']['percent_change_1h'].round(2) %></td>
        <td><%= crypto['quote']['USD']['percent_change_24h'].round(2) %></td>
        <td><%= crypto['quote']['USD']['percent_change_7d'].round(2) %></td>        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/lookup.html.erb
<h1>Search Crypto</h1>
<br/>

<%= form_with url: home_lookup_path do |f| %>
  <div class="row">
    <div class="col-md-2">
      <%= f.text_field :crypto_symbol, placeholder: 'Enter a symbol', class: "form-control" %>
      <%= f.submit "Smash here!", class: 'btn btn-default' %>
    </div>
  </div>
<% end %>
<br/><br/>

<% if @coin && @coin.empty? %>
  <% if !@symbol.empty? %>
    <% flash[:notice] = @symbol + " not found\n" %>
  <% else %>
    <% flash[:notice] = "Please enter a valid symbol!" %>
  <% end %>
<% elsif @coin %>
  <%= render 'home/single_coin_info_panel' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoPortfolioTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'home/navbar' %>
    <div class="container">
      <%= render 'home/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>